include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_typing_uninitialized_variables
    - prefer_const_constructors
    - prefer_relative_imports
    # - sort_constructors_first
    - sort_unnamed_constructors_first
    - sort_pub_dependencies

